### ISSUE TITLE
Bugs & errors

### ISSUE THREAD

**Issue by Jelly9912** [ImagicalCorp/SkyBlockPE#2]
1. Teleporting to the new island is really bad
2. Unknown error on /is clear
3. Closed server on /is reset

**Comment by thebigsmileXD** [comment]
Just saying:
To Do

quests and rewards
Configuration for exact island size, currently based on chunks
rewrite the generator
reset island fix
dispose/clear island fix
setspawn bug
spawn chests at correct position
change meta of leaves so they despawn and saplings drop

**Comment by keithkfng** [comment]
This is still in the development phrase. We will fix it when the time is right. Thanks for the bug report anyway.
