### ISSUE TITLE
error with /is auto command

### ISSUE THREAD

**Issue by nooneusethisname** [ImagicalCorp/SkyBlockPE#3]
players will be teleported outside the island :v

**Comment by thebigsmileXD** [comment]
When will you all finally start to read the readme?
-.-"

**Comment by nooneusethisname** [comment]
i read it, and this is just a issue, just a report

**Comment by thebigsmileXD** [comment]
1st. This is a duplicate.
2nd. This stands in the to-do list

**Comment by mucahit34** [comment]
how are we going to do
